package com.knitml.el.definition

enum KnittingKeyword { WITH_KEY, WITH_LABEL, TO, ST, STS, UNTIL, NEXT, RESET_ROW_COUNT, SILENTLY, ALL_STITCHES, DO_NOT_ASSIGN_NUMBER, INFORM_SIDE, WITH, IN_ROW, ON_NEEDLE, REMAIN, UNWORKED, LEFT, COUNT_AS_ROW, FLAT, ROUND }